"""
models.py — World Instruments Explorer veri katmanı
Tüm ses kaynakları Wikimedia Commons'tan (CC lisanslı).
"""

# ─────────────────────────────────────────────────────────────────────────────
# SES KAYNAKLARI
# ─────────────────────────────────────────────────────────────────────────────
AUDIO: dict[str, str] = {
    "didgeridoo":        "https://upload.wikimedia.org/wikipedia/commons/7/7c/Didgeridoo_sound.ogg",
    "sitar":             "https://upload.wikimedia.org/wikipedia/commons/1/17/Sitar_clipping.ogg",
    "tabla":             "https://upload.wikimedia.org/wikipedia/commons/e/e4/Tabla_solo_in_teental.ogg",
    "shamisen":          "https://upload.wikimedia.org/wikipedia/commons/a/a4/Shamisen_sample.ogg",
    "koto":              "https://upload.wikimedia.org/wikipedia/commons/9/9b/Koto_music.ogg",
    "shakuhachi":        "https://upload.wikimedia.org/wikipedia/commons/e/e8/Shakuhachi_sample.ogg",
    "taiko":             "https://upload.wikimedia.org/wikipedia/commons/c/cf/Taiko_drums.ogg",
    "erhu":              "https://upload.wikimedia.org/wikipedia/commons/d/d0/Erhu_sample.ogg",
    "guzheng":           "https://upload.wikimedia.org/wikipedia/commons/f/f1/Guzheng_music.ogg",
    "oud":               "https://upload.wikimedia.org/wikipedia/commons/f/f9/Oud_taksim.ogg",
    "bagpipes":          "https://upload.wikimedia.org/wikipedia/commons/6/6b/Bagpipes.ogg",
    "accordion":         "https://upload.wikimedia.org/wikipedia/commons/2/21/Accordion_riff.ogg",
    "balalaika":         "https://upload.wikimedia.org/wikipedia/commons/e/e5/Balalaika_music.ogg",
    "bouzouki":          "https://upload.wikimedia.org/wikipedia/commons/b/b6/Bouzouki_sample.ogg",
    "gayageum":          "https://upload.wikimedia.org/wikipedia/commons/8/8c/Gayageum_sanjo.ogg",
    "steel pan":         "https://upload.wikimedia.org/wikipedia/commons/9/9d/Steeldrum.ogg",
    "marimba":           "https://upload.wikimedia.org/wikipedia/commons/d/d4/Marimba_sample.ogg",
    "mbira":             "https://upload.wikimedia.org/wikipedia/commons/1/11/Mbira_music.ogg",
    "kora":              "https://upload.wikimedia.org/wikipedia/commons/5/50/Kora_music.ogg",
    "djembe":            "https://upload.wikimedia.org/wikipedia/commons/3/35/Djembe_sample.ogg",
    "bansuri":           "https://upload.wikimedia.org/wikipedia/commons/7/7c/Bansuri_sample.ogg",
    "hardanger fiddle":  "https://upload.wikimedia.org/wikipedia/commons/a/a1/Hardingfele.ogg",
    "kantele":           "https://upload.wikimedia.org/wikipedia/commons/b/b2/Kantele_sample.ogg",
    "nyckelharpa":       "https://upload.wikimedia.org/wikipedia/commons/4/4f/Nyckelharpa_sample.ogg",
    "duduk":             "https://upload.wikimedia.org/wikipedia/commons/7/73/Duduk_sample.ogg",
    "uilleann pipes":    "https://upload.wikimedia.org/wikipedia/commons/6/6f/Uilleann_pipes_sample.ogg",
    "charango":          "https://upload.wikimedia.org/wikipedia/commons/e/e4/Charango_sample.ogg",
    "gamelan":           "https://upload.wikimedia.org/wikipedia/commons/3/39/Gamelan_sample.ogg",
    "saung gauk":        "https://upload.wikimedia.org/wikipedia/commons/c/c9/Saung_gauk_sample.ogg",
    "morin khuur":       "https://upload.wikimedia.org/wikipedia/commons/6/6e/Morin_khuur.ogg",
}


# ─────────────────────────────────────────────────────────────────────────────
# YARDIMCI: JS objesini Python sözlüğüne dönüştürülmüş hali
# Her enstrüman: {emoji, name, description, audio_key}
# ─────────────────────────────────────────────────────────────────────────────
def _i(e: str, n: str, d: str, a=None):
    return {"emoji": e, "name": n, "description": d, "audio_key": a}


# ─────────────────────────────────────────────────────────────────────────────
# ÜLKE VERİSİ
# ─────────────────────────────────────────────────────────────────────────────
DATA: dict[str, dict] = {
    "Afghanistan": {"region": "Central Asia", "instruments": [
        _i("🎵", "Rubab", "Short-necked lute, national instrument"),
        _i("🎵", "Dutaar", "Long-necked 2-string lute"),
        _i("🥁", "Zerbaghali", "Goblet-shaped clay drum"),
        _i("🎺", "Sornay", "Double-reed wind instrument"),
    ]},
    "Albania": {"region": "Southern Europe", "instruments": [
        _i("🎵", "Lahuta", "Single-stringed bowed fiddle of the north"),
        _i("🎵", "Çifteli", "2-stringed plucked lute"),
        _i("🎺", "Zumarë", "Double-reed clarinet"),
        _i("🥁", "Lodër", "Frame drum"),
    ]},
    "Algeria": {"region": "North Africa", "instruments": [
        _i("🎵", "Guembri", "3-string bass lute of Gnawa music"),
        _i("🥁", "Bendir", "Frame drum with snare"),
        _i("🎺", "Gasba", "Open-ended reed flute"),
        _i("🎵", "Oud", "Classical Arabic lute", "oud"),
    ]},
    "Angola": {"region": "Central Africa", "instruments": [
        _i("🎵", "Mbira", "Thumb piano", "mbira"),
        _i("🥁", "Ngoma", "Double-headed drum"),
        _i("🎵", "Kissange", "Lamellaphone with wooden keys"),
        _i("🎺", "Hungu", "Musical bow"),
    ]},
    "Argentina": {"region": "South America", "instruments": [
        _i("🪗", "Bandoneón", "Button concertina essential for tango"),
        _i("🎸", "Guitar", "Classical guitar for folk music"),
        _i("🎻", "Violin", "Tango orchestra violin"),
        _i("🥁", "Bombo Leguero", "Large folkloric drum"),
    ]},
    "Armenia": {"region": "Caucasus", "instruments": [
        _i("🎺", "Duduk", "Ancient double-reed apricot wood flute", "duduk"),
        _i("🎵", "Kanon", "Plucked zither"),
        _i("🥁", "Dhol", "Double-headed barrel drum"),
        _i("🎵", "Kamancha", "Bowed spike fiddle"),
    ]},
    "Australia": {"region": "Oceania", "instruments": [
        _i("🎺", "Didgeridoo", "Wind instrument, Aboriginal Australians", "didgeridoo"),
        _i("🥁", "Clapping Sticks", "Wooden percussion sticks"),
        _i("🎵", "Bullroarer", "Ancient whirled ceremonial instrument"),
        _i("🪘", "Bilma", "Hardwood clapsticks used in ceremony"),
    ]},
    "Austria": {"region": "Central Europe", "instruments": [
        _i("🎵", "Zither", "Alpine plucked string instrument"),
        _i("🎺", "Alphorn", "Long natural horn"),
        _i("🪗", "Steirische Harmonika", "Diatonic button accordion", "accordion"),
        _i("🎻", "Fiddle", "Alpine folk fiddle"),
    ]},
    "Azerbaijan": {"region": "Caucasus", "instruments": [
        _i("🎵", "Tar", "Double-bellied long-necked lute"),
        _i("🎵", "Kamancha", "Bowed spike fiddle"),
        _i("🥁", "Nagara", "Cylindrical drum"),
        _i("🎵", "Saz", "Long-necked lute"),
    ]},
    "Bangladesh": {"region": "South Asia", "instruments": [
        _i("🎵", "Dotara", "2-stringed plucked lute"),
        _i("🥁", "Dhol", "Barrel drum"),
        _i("🎺", "Bansuri", "Bamboo flute", "bansuri"),
        _i("🎵", "Ektara", "One-string drone lute of bauls"),
    ]},
    "Belgium": {"region": "Western Europe", "instruments": [
        _i("🪗", "Accordion", "Popular in Flemish folk dances", "accordion"),
        _i("🎵", "Carillon", "Tower bell instrument, UNESCO heritage"),
        _i("🎻", "Fiddle", "Flemish folk fiddle"),
        _i("🎺", "Saxophone", "Invented by Belgian Adolphe Sax"),
    ]},
    "Bolivia": {"region": "South America", "instruments": [
        _i("🎺", "Siku (Zampoña)", "Pan flute of the Andes"),
        _i("🎺", "Quena", "Notched end flute"),
        _i("🎵", "Charango", "Small 10-string Andean lute", "charango"),
        _i("🥁", "Bombo", "Large Andean bass drum"),
    ]},
    "Brazil": {"region": "South America", "instruments": [
        _i("🥁", "Surdo", "Bass drum for samba rhythms"),
        _i("🎸", "Cavaquinho", "Small 4-string guitar"),
        _i("🪘", "Pandeiro", "Brazilian tambourine"),
        _i("🎵", "Berimbau", "Bow instrument used in capoeira"),
    ]},
    "Bulgaria": {"region": "Southeast Europe", "instruments": [
        _i("🎺", "Gaida", "Bulgarian bagpipe", "bagpipes"),
        _i("🎵", "Gadulka", "Bowed string instrument"),
        _i("🎺", "Kaval", "End-blown flute"),
        _i("🥁", "Tapan", "Double-headed drum"),
    ]},
    "Cambodia": {"region": "Southeast Asia", "instruments": [
        _i("🪗", "Roneat", "Bamboo xylophone"),
        _i("🎵", "Tro Khmer", "Bowed string instrument"),
        _i("🎺", "Sralai", "Quadruple-reed oboe"),
        _i("🥁", "Skor Thom", "Large barrel drum"),
    ]},
    "Canada": {"region": "North America", "instruments": [
        _i("🎻", "Fiddle", "Celtic and Métis fiddle traditions"),
        _i("🎵", "Jaw Harp", "Used by Indigenous peoples"),
        _i("🪗", "Accordion", "In Acadian and Québécois music", "accordion"),
        _i("🥁", "Pow Wow Drum", "Sacred drum of First Nations"),
    ]},
    "Chile": {"region": "South America", "instruments": [
        _i("🎺", "Trutruka", "Long Mapuche trumpet"),
        _i("🥁", "Kultrún", "Sacred Mapuche frame drum"),
        _i("🎸", "Guitarrón Chileno", "25-string guitar, UNESCO heritage"),
        _i("🎺", "Quena", "Andean notched flute"),
    ]},
    "China": {"region": "East Asia", "instruments": [
        _i("🎵", "Erhu", "2-stringed bowed fiddle", "erhu"),
        _i("🎵", "Pipa", "4-string pear-shaped lute"),
        _i("🪗", "Guzheng", "21-string plucked zither", "guzheng"),
        _i("🎺", "Dizi", "Transverse bamboo flute"),
    ]},
    "Colombia": {"region": "South America", "instruments": [
        _i("🪗", "Vallenato Accordion", "Diatonic button accordion", "accordion"),
        _i("🥁", "Caja Drum", "Small cylindrical drum"),
        _i("🎵", "Gaita", "Indigenous flute of Zenú peoples"),
        _i("🪘", "Maracas", "Gourd rattles"),
    ]},
    "Cuba": {"region": "Caribbean", "instruments": [
        _i("🥁", "Conga", "Tall narrow-headed Afro-Cuban drum"),
        _i("🎸", "Tres", "Cuban guitar with 3 pairs of strings"),
        _i("🪘", "Bongos", "Pair of small open-bottomed drums"),
        _i("🎺", "Trumpet", "Lead melody in son cubano"),
    ]},
    "Czech Republic": {"region": "Central Europe", "instruments": [
        _i("🪗", "Dudy", "Czech bagpipe", "bagpipes"),
        _i("🎻", "Fiddle", "Folk violin in Moravian music"),
        _i("🎵", "Cimbál", "Hammered dulcimer"),
        _i("🎺", "Flute", "Shepherd's flute"),
    ]},
    "Denmark": {"region": "Northern Europe", "instruments": [
        _i("🎺", "Lur", "Bronze Age curved horn"),
        _i("🎻", "Violin", "Folk violin in Danish folk music"),
        _i("🪗", "Accordion", "Common in Danish folk", "accordion"),
        _i("🥁", "Frame Drum", "Viking-era percussion"),
    ]},
    "Ecuador": {"region": "South America", "instruments": [
        _i("🎺", "Quena", "Andean notched flute"),
        _i("🎺", "Pingullo", "3-holed flute of indigenous people"),
        _i("🥁", "Bombo", "Large drum"),
        _i("🎵", "Charango", "Small Andean lute", "charango"),
    ]},
    "Egypt": {"region": "North Africa", "instruments": [
        _i("🎵", "Oud", "Short-necked lute, ancestor of the guitar", "oud"),
        _i("🥁", "Doumbek", "Goblet-shaped drum"),
        _i("🎺", "Nay", "Ancient reed flute"),
        _i("🎵", "Kanun", "Trapezoidal plucked zither"),
    ]},
    "Estonia": {"region": "Northern Europe", "instruments": [
        _i("🎵", "Kannel", "Estonian zither (psaltery)"),
        _i("🎺", "Torupill", "Bagpipe made from animal stomach", "bagpipes"),
        _i("🎻", "Fiddle", "Folk violin"),
        _i("🪘", "Talharpa", "Ancient bowed lyre"),
    ]},
    "Ethiopia": {"region": "East Africa", "instruments": [
        _i("🎵", "Krar", "6-string lyre"),
        _i("🎺", "Washint", "Bamboo flute"),
        _i("🥁", "Kebero", "Conical double-headed drum"),
        _i("🎵", "Masenqo", "Single-string bowed fiddle"),
    ]},
    "Finland": {"region": "Northern Europe", "instruments": [
        _i("🎵", "Kantele", "National instrument, plucked zither", "kantele"),
        _i("🎺", "Jouhikko", "Bowed lyre"),
        _i("🎺", "Pilli", "Willow bark flute"),
        _i("🪗", "Harmonikka", "Finnish button accordion", "accordion"),
    ]},
    "France": {"region": "Western Europe", "instruments": [
        _i("🪗", "Accordion", "Button or piano accordion, icon of French music", "accordion"),
        _i("🎵", "Musette", "Small bellows-blown bagpipe"),
        _i("🎻", "Vielle à roue", "Hurdy-gurdy with a rosined wheel"),
        _i("🎺", "Cor de chasse", "Circular hunting horn"),
    ]},
    "Gambia": {"region": "West Africa", "instruments": [
        _i("🎵", "Kora", "21-string harp-lute of the Mandé", "kora"),
        _i("🪗", "Balafon", "Gourd-resonated xylophone"),
        _i("🥁", "Djembe", "Goblet drum", "djembe"),
        _i("🎵", "Ngoni", "Ancient plucked lute"),
    ]},
    "Georgia": {"region": "Caucasus", "instruments": [
        _i("🎵", "Panduri", "3-string plucked lute"),
        _i("🎵", "Chonguri", "4-string plucked lute"),
        _i("🎺", "Duduki", "Double-reed woodwind"),
        _i("🥁", "Doli", "Double-headed drum"),
    ]},
    "Germany": {"region": "Western Europe", "instruments": [
        _i("🎺", "Alphorn", "Long natural horn from Alpine regions"),
        _i("🪘", "Hackbrett", "Hammered dulcimer"),
        _i("🎺", "Waldhorn", "French horn, perfected in Germany"),
        _i("🎵", "Lute", "Renaissance plucked string instrument"),
    ]},
    "Ghana": {"region": "West Africa", "instruments": [
        _i("🥁", "Fontomfrom", "Royal court drums"),
        _i("🎵", "Kora", "21-string bridge harp", "kora"),
        _i("🪗", "Gyil", "West African xylophone"),
        _i("🎺", "Atenteben", "Bamboo flute"),
    ]},
    "Greece": {"region": "Southern Europe", "instruments": [
        _i("🎵", "Bouzouki", "Long-necked plucked lute, icon of rebetiko", "bouzouki"),
        _i("🎻", "Lyra", "Bowed pear-shaped fiddle"),
        _i("🪘", "Tzouras", "Smaller bouzouki variant"),
        _i("🪗", "Accordion", "Adopted into laïkó music", "accordion"),
    ]},
    "Guatemala": {"region": "Central America", "instruments": [
        _i("🪗", "Marimba", "National instrument, wooden xylophone", "marimba"),
        _i("🥁", "Tun", "Maya slit drum"),
        _i("🎺", "Chirimía", "Double-reed oboe"),
        _i("🎺", "Tzicolaj", "Maya bone flute"),
    ]},
    "Guinea": {"region": "West Africa", "instruments": [
        _i("🎵", "Kora", "21-string harp-lute", "kora"),
        _i("🪗", "Balafon", "Xylophone"),
        _i("🥁", "Djembe", "West African goblet drum", "djembe"),
        _i("🎵", "Bolon", "3-string arched harp"),
    ]},
    "Hungary": {"region": "Central Europe", "instruments": [
        _i("🎻", "Cimbalom", "Large concert hammered dulcimer"),
        _i("🎻", "Tárogató", "Wooden single-reed wind instrument"),
        _i("🪗", "Tekerőlant", "Hungarian hurdy-gurdy"),
        _i("🎺", "Koboz", "Short-necked lute"),
    ]},
    "Iceland": {"region": "Northern Europe", "instruments": [
        _i("🎵", "Langspil", "2-string bowed drone zither"),
        _i("🎵", "Fiðla", "Icelandic fiddle"),
        _i("🎺", "Lúðr", "Ancient wooden horn"),
        _i("🪘", "Frame Drum", "Shamanic frame drum"),
    ]},
    "India": {"region": "South Asia", "instruments": [
        _i("🎵", "Sitar", "Long-necked plucked lute", "sitar"),
        _i("🥁", "Tabla", "Pair of hand drums", "tabla"),
        _i("🎵", "Veena", "Ancient plucked string instrument"),
        _i("🎺", "Bansuri", "Bamboo transverse flute", "bansuri"),
    ]},
    "Indonesia": {"region": "Southeast Asia", "instruments": [
        _i("🪗", "Gamelan", "Tuned bronze percussion ensemble", "gamelan"),
        _i("🎵", "Angklung", "Bamboo shaken instrument, UNESCO heritage"),
        _i("🎸", "Kacapi", "Zither from Sundanese music"),
        _i("🪘", "Kendang", "Double-headed barrel drum"),
    ]},
    "Iran": {"region": "Middle East", "instruments": [
        _i("🎵", "Tar", "Long-necked plucked lute"),
        _i("🎵", "Santur", "Hammered dulcimer"),
        _i("🎺", "Ney", "Reed flute"),
        _i("🥁", "Tombak", "Goblet drum"),
    ]},
    "Iraq": {"region": "Middle East", "instruments": [
        _i("🎵", "Oud", "Classical Arabic lute", "oud"),
        _i("🥁", "Tabla", "Goblet-shaped drum"),
        _i("🎺", "Joza", "4-string spike fiddle"),
        _i("🎵", "Santur", "Hammered dulcimer"),
    ]},
    "Ireland": {"region": "Northern Europe", "instruments": [
        _i("🎻", "Uilleann Pipes", "Bellows-blown Irish bagpipe", "uilleann pipes"),
        _i("🪘", "Bodhrán", "Frame drum played with a tipper"),
        _i("🎻", "Fiddle", "Irish style violin"),
        _i("🪗", "Concertina", "Hexagonal free-reed instrument"),
    ]},
    "Israel": {"region": "Middle East", "instruments": [
        _i("🎺", "Shofar", "Ram's horn blown on High Holy Days"),
        _i("🎵", "Kinnor", "Ancient biblical lyre"),
        _i("🎵", "Oud", "Arabic lute in Mizrahi music", "oud"),
        _i("🥁", "Darbuka", "Goblet drum"),
    ]},
    "Italy": {"region": "Southern Europe", "instruments": [
        _i("🎵", "Mandolin", "8-string plucked lute from Naples"),
        _i("🪗", "Organetto", "Diatonic button accordion", "accordion"),
        _i("🎺", "Zampogna", "Southern Italian bagpipe", "bagpipes"),
        _i("🥁", "Tamburello", "Southern Italian tambourine"),
    ]},
    "Jamaica": {"region": "Caribbean", "instruments": [
        _i("🥁", "Nyahbinghi Drum", "Rastafarian ceremonial drum set"),
        _i("🎵", "Steel Pan", "Caribbean tuned percussion", "steel pan"),
        _i("🎸", "Bass Guitar", "Foundation of reggae music"),
        _i("🪗", "Melodica", "Keyboard wind instrument in ska/reggae"),
    ]},
    "Japan": {"region": "East Asia", "instruments": [
        _i("🎵", "Shamisen", "3-string lute played with a plectrum", "shamisen"),
        _i("🎋", "Shakuhachi", "Bamboo end-blown flute", "shakuhachi"),
        _i("🥁", "Taiko", "Large ceremonial drums", "taiko"),
        _i("🎵", "Koto", "13-string zither", "koto"),
    ]},
    "Jordan": {"region": "Middle East", "instruments": [
        _i("🎵", "Rababa", "Spike fiddle of Bedouin tradition"),
        _i("🎵", "Oud", "Arabic lute", "oud"),
        _i("🥁", "Tabla", "Goblet drum"),
        _i("🎺", "Nay", "Reed flute"),
    ]},
    "Kenya": {"region": "East Africa", "instruments": [
        _i("🎵", "Nyatiti", "8-string lyre of the Luo"),
        _i("🥁", "Ingoma", "Double-headed drum"),
        _i("🎺", "Orutu", "One-string fiddle"),
        _i("🎵", "Litungu", "Luhya 8-string lyre"),
    ]},
    "South Korea": {"region": "East Asia", "instruments": [
        _i("🎵", "Gayageum", "12-string zither", "gayageum"),
        _i("🥁", "Janggu", "Hourglass drum"),
        _i("🎺", "Daegeum", "Large transverse bamboo flute"),
        _i("🎵", "Haegeum", "2-string fiddle"),
    ]},
    "Mexico": {"region": "Central America", "instruments": [
        _i("🎸", "Guitarrón", "Large 6-string bass guitar of mariachi"),
        _i("🎺", "Trumpet", "Lead melody in mariachi"),
        _i("🎻", "Violin", "Mariachi violin"),
        _i("🥁", "Teponaztli", "Maya slit drum"),
    ]},
    "Mongolia": {"region": "Central Asia", "instruments": [
        _i("🎵", "Morin Khuur", "Horse-head fiddle", "morin khuur"),
        _i("🎺", "Tsuur", "Three-holed flute"),
        _i("🥁", "Shaman Drum", "Frame drum"),
        _i("🎵", "Yatga", "Plucked zither"),
    ]},
    "Morocco": {"region": "North Africa", "instruments": [
        _i("🎵", "Oud", "Arabic lute", "oud"),
        _i("🥁", "Bendir", "Frame drum"),
        _i("🎺", "Ghaita", "Double-reed wind"),
        _i("🎵", "Guembri", "3-string bass lute of Gnawa", "mbira"),
    ]},
    "Myanmar": {"region": "Southeast Asia", "instruments": [
        _i("🎵", "Saung Gauk", "Arched harp, national instrument", "saung gauk"),
        _i("🥁", "Pat Waing", "Circle of 21 tuned drums"),
        _i("🎺", "Hne", "Double-reed oboe"),
        _i("🎵", "Pattala", "Bamboo xylophone"),
    ]},
    "Netherlands": {"region": "Western Europe", "instruments": [
        _i("🎵", "Carillon", "Tower bells, UNESCO heritage"),
        _i("🪗", "Accordion", "Dutch folk accordion", "accordion"),
        _i("🎻", "Fiddle", "Dutch folk violin"),
        _i("🎺", "Flute", "Dutch recorder tradition"),
    ]},
    "Nigeria": {"region": "West Africa", "instruments": [
        _i("🥁", "Talking Drum", "Hourglass pressure drum"),
        _i("🎵", "Kora", "Harp-lute", "kora"),
        _i("🪗", "Balafon", "Xylophone"),
        _i("🎺", "Kakaki", "Long ceremonial trumpet"),
    ]},
    "Norway": {"region": "Northern Europe", "instruments": [
        _i("🎻", "Hardanger Fiddle", "8-string sympathetic violin", "hardanger fiddle"),
        _i("🎺", "Lur", "Bronze Age horn"),
        _i("🪗", "Accordion", "Norwegian folk accordion", "accordion"),
        _i("🎵", "Langeleik", "Drone zither"),
    ]},
    "Pakistan": {"region": "South Asia", "instruments": [
        _i("🎵", "Sitar", "Long-necked lute", "sitar"),
        _i("🥁", "Tabla", "Pair of hand drums", "tabla"),
        _i("🎺", "Bansuri", "Bamboo flute", "bansuri"),
        _i("🎵", "Rubab", "Short-necked lute"),
    ]},
    "Peru": {"region": "South America", "instruments": [
        _i("🎺", "Quena", "Notched flute of the Andes"),
        _i("🎺", "Siku", "Pan flute"),
        _i("🎵", "Charango", "10-string Andean lute", "charango"),
        _i("🥁", "Cajón", "Box drum of Afro-Peruvian music"),
    ]},
    "Philippines": {"region": "Southeast Asia", "instruments": [
        _i("🎵", "Kudyapi", "2-string boat lute"),
        _i("🪘", "Kulintang", "Gong chime"),
        _i("🥁", "Dabakan", "Single-headed drum"),
        _i("🎺", "Flute", "Bamboo nose flute"),
    ]},
    "Poland": {"region": "Eastern Europe", "instruments": [
        _i("🎻", "Mazanki", "Small folk violin"),
        _i("🪗", "Accordion", "In mazurka and polka", "accordion"),
        _i("🎺", "Dudy", "Polish bagpipe", "bagpipes"),
        _i("🥁", "Bęben", "Frame drum"),
    ]},
    "Portugal": {"region": "Southern Europe", "instruments": [
        _i("🎸", "Fado Guitar (Portuguese)", "12-string teardrop guitar"),
        _i("🎸", "Viola Braguesa", "5-course guitar from Braga"),
        _i("🪗", "Accordion", "In folk dances", "accordion"),
        _i("🎵", "Cavaquinho", "Small 4-string guitar"),
    ]},
    "Romania": {"region": "Eastern Europe", "instruments": [
        _i("🎻", "Cobza", "Short-necked lute"),
        _i("🎺", "Nai", "Pan flute"),
        _i("🪗", "Accordion", "In folk music", "accordion"),
        _i("🎵", "Cimbalom", "Hammered dulcimer"),
    ]},
    "Russia": {"region": "Eastern Europe", "instruments": [
        _i("🎵", "Balalaika", "Triangular 3-string lute", "balalaika"),
        _i("🎵", "Gusli", "Multi-string psaltery"),
        _i("🪗", "Bayan", "Russian button accordion", "accordion"),
        _i("🎺", "Zhaleika", "Reed horn"),
    ]},
    "Saudi Arabia": {"region": "Middle East", "instruments": [
        _i("🎵", "Oud", "Arabic lute", "oud"),
        _i("🥁", "Tabla", "Goblet drum"),
        _i("🎺", "Mizmar", "Double-reed instrument"),
        _i("🎵", "Rababa", "Spike fiddle"),
    ]},
    "Scotland": {"region": "Northern Europe", "instruments": [
        _i("🎺", "Bagpipes", "Great Highland Bagpipe", "bagpipes"),
        _i("🎻", "Fiddle", "Scottish folk fiddle"),
        _i("🎵", "Clarsach", "Celtic harp"),
        _i("🪗", "Accordion", "Scottish country dances", "accordion"),
    ]},
    "Senegal": {"region": "West Africa", "instruments": [
        _i("🎵", "Kora", "21-string harp-lute", "kora"),
        _i("🥁", "Djembe", "Goblet drum", "djembe"),
        _i("🪗", "Balafon", "Xylophone"),
        _i("🥁", "Sabar", "Tall single-headed drum"),
    ]},
    "South Africa": {"region": "Southern Africa", "instruments": [
        _i("🎵", "Mbira", "Thumb piano", "mbira"),
        _i("🥁", "Djembe", "Goblet drum", "djembe"),
        _i("🎵", "Uhadi", "Musical bow"),
        _i("🪗", "Concertina", "In boeremusiek"),
    ]},
    "Spain": {"region": "Southern Europe", "instruments": [
        _i("🎸", "Classical Guitar", "Flamenco and classical tradition"),
        _i("🪗", "Castanets", "Wooden rhythm clappers"),
        _i("🎵", "Bandurria", "12-string plucked lute"),
        _i("🎺", "Gaita", "Galician bagpipe", "bagpipes"),
    ]},
    "Sweden": {"region": "Northern Europe", "instruments": [
        _i("🎻", "Nyckelharpa", "Keyed fiddle, UNESCO heritage", "nyckelharpa"),
        _i("🎵", "Hurdy-Gurdy", "Wheel-bowed string instrument"),
        _i("🪗", "Accordion", "In Swedish folk music", "accordion"),
        _i("🎻", "Fiddle", "Swedish folk violin"),
    ]},
    "Switzerland": {"region": "Central Europe", "instruments": [
        _i("🎺", "Alphorn", "Long wooden mountain horn"),
        _i("🎵", "Hackbrett", "Hammered dulcimer"),
        _i("🎺", "Büchel", "Curved alpine horn"),
        _i("🪗", "Accordion", "In Ländler folk music", "accordion"),
    ]},
    "Tanzania": {"region": "East Africa", "instruments": [
        _i("🥁", "Ngoma", "Cylindrical drum"),
        _i("🎵", "Zeze", "Single-string fiddle"),
        _i("🎺", "Filimbi", "Reed flute"),
        _i("🎵", "Marimba", "Wooden xylophone", "marimba"),
    ]},
    "Thailand": {"region": "Southeast Asia", "instruments": [
        _i("🪗", "Ranat Ek", "Wooden xylophone"),
        _i("🎺", "Pi Nai", "Quadruple-reed oboe"),
        _i("🥁", "Taphon", "Barrel drum"),
        _i("🎵", "Saw Duang", "2-string fiddle"),
    ]},
    "Trinidad and Tobago": {"region": "Caribbean", "instruments": [
        _i("🎵", "Steel Pan", "Tuned percussion from oil drums", "steel pan"),
        _i("🥁", "Tassa Drum", "Goatskin drum in Indian tradition"),
        _i("🎸", "Cuatro", "4-string guitar"),
        _i("🪘", "Shak-Shak", "Gourd rattle"),
    ]},
    "Turkey": {"region": "Middle East", "instruments": [
        _i("🎵", "Saz (Bağlama)", "Long-necked lute, national instrument"),
        _i("🎵", "Oud", "Short-necked lute", "oud"),
        _i("🥁", "Davul", "Double-headed bass drum"),
        _i("🎺", "Zurna", "Double-reed wind instrument"),
    ]},
    "Uganda": {"region": "East Africa", "instruments": [
        _i("🎵", "Adungu", "Arched harp of the Acholi"),
        _i("🥁", "Engoma", "Royal drum"),
        _i("🎵", "Endingidi", "One-string fiddle"),
        _i("🪗", "Amadinda", "Xylophone"),
    ]},
    "Ukraine": {"region": "Eastern Europe", "instruments": [
        _i("🎵", "Bandura", "Multi-string plucked lute"),
        _i("🎵", "Kobza", "Short-necked lute"),
        _i("🎺", "Sopilka", "Wooden flute"),
        _i("🪗", "Accordion", "In Ukrainian folk", "accordion"),
    ]},
    "United Kingdom": {"region": "Northern Europe", "instruments": [
        _i("🎺", "Bagpipes", "Highland bagpipe", "bagpipes"),
        _i("🎻", "Fiddle", "English folk fiddle"),
        _i("🪗", "Concertina", "Hexagonal free-reed instrument"),
        _i("🥁", "Bodhrán", "Celtic frame drum"),
    ]},
    "United States": {"region": "North America", "instruments": [
        _i("🎸", "Banjo", "5-string plucked instrument of Appalachia"),
        _i("🎻", "Fiddle", "American folk violin"),
        _i("🎺", "Blues Harmonica", "Diatonic harmonica"),
        _i("🎸", "Steel Guitar", "Hawaiian-style lap steel"),
    ]},
    "Uzbekistan": {"region": "Central Asia", "instruments": [
        _i("🎵", "Dutar", "2-string long-necked lute"),
        _i("🎵", "Rubab", "Short-necked plucked lute"),
        _i("🥁", "Doira", "Frame drum"),
        _i("🎺", "Nay", "Reed flute"),
    ]},
    "Venezuela": {"region": "South America", "instruments": [
        _i("🎸", "Cuatro", "4-string national guitar"),
        _i("🪘", "Maracas", "Gourd rattles, national symbol"),
        _i("🥁", "Tambor", "African-origin drum in joropo"),
        _i("🎵", "Arpa Llanera", "Plains harp, icon of joropo music"),
    ]},
    "Vietnam": {"region": "Southeast Asia", "instruments": [
        _i("🎵", "Đàn bầu", "Single-string zither with whammy bar"),
        _i("🎵", "Đàn tranh", "16-string zither"),
        _i("🎺", "Sáo trúc", "Bamboo transverse flute"),
        _i("🥁", "Trống cơm", "Double-headed cooked-rice drum"),
    ]},
    "Yemen": {"region": "Middle East", "instruments": [
        _i("🎵", "Oud", "Arabic lute", "oud"),
        _i("🎺", "Mizmar", "Wooden double-reed instrument"),
        _i("🥁", "Marfa", "Large cylindrical drum"),
        _i("🎵", "Simsimiyya", "5-string lyre of Red Sea coast"),
    ]},
    "Zimbabwe": {"region": "Southern Africa", "instruments": [
        _i("🎵", "Mbira Dzavadzimu", "Spirit voice thumb piano, UNESCO heritage", "mbira"),
        _i("🪗", "Marimba", "Wooden xylophone", "marimba"),
        _i("🥁", "Ngoma", "Drum"),
        _i("🎺", "Chipendani", "Mouth bow"),
    ]},
}
